SCR_MissionHeaderCampaign {
 World "{8D277CCCDC30A8FC}HaangGong_ConflictMission.ent"
 m_sName "<Insert world name>"
 m_sAuthor "<Insert your name>"
 m_sDescription "<Insert world description>"
 m_sGameMode "#AR-Campaign_GamemodeName"
 m_iPlayerCount 64
 m_eEditableGameFlags 6
 m_eDefaultGameFlags 6
 m_bRandomStartingDaytime 1
 m_bRandomStartingWeather 1
 m_bRandomWeatherChanges 1
 m_fXpMultiplier 2
 m_iMapMarkerLimitPerPlayer 20
}